name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest faker httpx fastapi uvicorn sqlalchemy pandas

    - name: Exporta variáveis de ambiente
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Verifica variável DATABASE_URL
      run: |
        if [ -z "$DATABASE_URL" ]; then
          echo "DATABASE_URL não está definida!"
          exit 1
        else
          echo "DATABASE_URL detectada: $DATABASE_URL"
        fi

    - name: Roda testes
      run: pytest tests/ --maxfail=1 --disable-warnings -v
